### ISSUE TITLE
Asciidoc scanner fails with definition lists

### ISSUE THREAD

**Issue by DirkMahler** [kontext-e/jqassistant-plugins#43]
Trying to scan an .adoc file which contains definition lists:

`
MyTerm::
The definition of my term
`

The following error is reported:

`
Error while scanning Asciidoc block dlist; reason is: java.lang.ClassCastException: org.jruby.specialized.RubyArrayTwoObject cannot be cast to org.asciidoctor.ast.AbstractBlock
`

**Comment by kontext-e** [comment]
Traced it down and find the cause in Asciidoctor 1.5.4.1 used by jQA 1.2.0. Implemented a workaround.
