### ISSUE TITLE
Git-Scanner shall store information about renamed files

### ISSUE THREAD

**Issue by DirkMahler** [kontext-e/jqassistant-plugins#46]
For doing historical analysis on git repos would be very helpful to see, if a file has been renamed. The current data model does not provide this information:

```
(:Commit)-[:CONTAINS_CHANGE]->(:Change)-[:MODIFIES]->(:File)
```
The change node provides the `modificationKind` property indicating the type of the change but in case of rename only the new file name is available. 
The interesting question is how this could be modeled, e.g. by additional ADDS/DELETES relation to a the old file?

```
(:Commit)-[:CONTAINS_CHANGE]->(change:Change)-[:MODIFIES]->(old:File)
(change)-[:DELETES]->(old:File),
(change)-[:CREATES]->(new:File)
```

Maybe the `modificationKind` property could be replaced by dedicated relations:

```
// create a file
(:Commit)-[:CONTAINS_CHANGE]->(:Change)-[:CREATES]->(:File) 
// update a file
(:Commit)-[:CONTAINS_CHANGE]->(:Change)-[:UPDATES]->(:File) 
// delete a file
(:Commit)-[:CONTAINS_CHANGE]->(:Change)-[:DELETES]->(:File)
// rename a file
(:Commit)-[:CONTAINS_CHANGE]->(c:Change)-[:RENAMES]->(old:File),
(c)-[:DELETES]->(old:File)
(c)-[:CREATES]->(new:File)
```
For compatibility reasons the MODIFIES relation could be kept over some releases to provide a migration path.

@jensnerche Do you think this would be the right way? If you agree I could implement it and come back with a pull request.

**Comment by kontext-e** [comment]
As I needed to become more familiar with Gerds changes I did the ticket by myself.

Yes, I think it is the right way to be more explicit. But for compatibility reasons I would
the MODIFIES relation untouched, esp. this one:
(:Commit)-[:CONTAINS_CHANGE]->(change:Change)-[:MODIFIES]->(new:File)

But I added the new relations as you suggested:
// create a file
(:Commit)-[:CONTAINS_CHANGE]->(:Change)-[:CREATES]->(:File) 
// update a file
(:Commit)-[:CONTAINS_CHANGE]->(:Change)-[:UPDATES]->(:File) 
// delete a file
(:Commit)-[:CONTAINS_CHANGE]->(:Change)-[:DELETES]->(:File)
// rename a file
(:Commit)-[:CONTAINS_CHANGE]->(c:Change)-[:RENAMES]->(old:File),
(c)-[:DELETES]->(old:File)
(c)-[:CREATES]->(new:File)

I also added the COPIES relation:
// copy a file
(:Commit)-[:CONTAINS_CHANGE]->(c:Change)-[:COPIES]->(old:File),
(c)-[:CREATES]->(new:File)

In additions there are also relationships for renamed files:
(old:File)-[:HAS_NEW_NAME]->(new:File)

and for copied files:
(old:Git:File)-[:COPY_OF]->(new:Git:File)

Does this match your needs?

**Comment by kontext-e** [comment]
Released it, so if you need more stuff, please open a new ticket.
