### ISSUE TITLE
Improvements to Asciidoc Table graph model

### ISSUE THREAD

**Issue by DirkMahler** [kontext-e/jqassistant-plugins#60]
The model for tables generated by the Asciidoc plugin should be improved:

1.Relationship types are inconsistent or misleading
- BODY -> HAS_ROW and HEADER -> HAS_HEADER_ROW for better readability of the graph
- COLUMNS -> HAS_COLUMN 
- CONTAINS_CELLS -> CONTAINS_CELL as the relationship refers to a single cell
2. Row nodes should have a rownumber property (similar to colnumber for Column nodes)
3. There should be relation from Cell nodes to the column they belong to e.g. ```(:Cell)-[OF_COLUMN]->(:Column)```, thus the colnumber attribute can be ommitted

**Comment by kontext-e** [comment]
Will be in 1.4.1

**Comment by DirkMahler** [comment]
Thanks!
