### ISSUE TITLE
Better Support for the Committer of an Commit

### ISSUE THREAD

**Issue by obfischer** [kontext-e/jqassistant-plugins#64]
As A user I would like to have the same support for the commiter of an commit as for the author. Therefore I would be happy to see the commiter in the graph modell provided by the Git plugin as own node.

**Comment by kontext-e** [comment]
For details about author and committer, see 'Pro Git' book:
https://git-scm.com/book/en/v2/Git-Basics-Viewing-the-Commit-History

As a consequence, Author and Committer need the same support in the graph.

As another consequence, 
(Author)-[:COMMITTED]->(Commit) could be changed to
(Author)-[:AUTHORED]->Commit)
Drawbacks are lost backwards compatibility and slightly more complicated queries
when to find Authors as well as Committers. So this change is not be done.

**Comment by kontext-e** [comment]
Available in 1.7.0-SNAPSHOT
