### ISSUE TITLE
JaCoCo plugins slows down scanning

### ISSUE THREAD

**Issue by DirkMahler** [kontext-e/jqassistant-plugins#67]
Adding the JaCoco plugin to jQA leads to a general and notable decrease in scanning performance. This is caused by the accepts method calling fileResource.getFile() which is potentially expensive if the fileResource is located in an archive (e.g. JAR file).
It should be verified if this method call can be avoided at all or the cheaper check for the XML file extension can be performed before accessing the file itself.

**Comment by kontext-e** [comment]
Same applies for PMD, SpotBugs/FindBugs and Checkstyle.
