### ISSUE TITLE
Adopt XO related annotations for jQA 1.8

### ISSUE THREAD

**Issue by DirkMahler** [kontext-e/jqassistant-plugins#68]
The release of jQA 1.8.0 will come with an XO release that enforces property related annotations to be present on getters, any presence of @Property or @Relationship or @Incoming/@Outgoing on a setter leads to an XOException when starting up.

This means that code like 

```
    @Property("context")
    void setContext(String context);
    String getContext();
```

must be migrated to

```
    @Property("context")
    String getContext();
    void setContext(String context);
```

or even simpler (if the name of the property can be resolved using a naming convention):

```
    String getContext();
    void setContext(String context);
```

**Comment by kontext-e** [comment]
PR was merged, thank you!
