### ISSUE TITLE
Scanning multiple git repositories in one shot

### ISSUE THREAD

**Issue by hmozaffari** [kontext-e/jqassistant-plugins#72]
When I try to scan multiple git repositories in one shot with CLI ( i.e. scan -f dir1/.git, dir2/.git, dir3/.git ) , plugin only detects git in first folder and ignores others. Seems logic is withheld in line bellow: 

https://github.com/kontext-e/jqassistant-plugins/blob/b7a5426a6b10ae81c156ed3d05c1e30bbcf0e894/git/src/main/java/de/kontext_e/jqassistant/plugin/git/scanner/GitScannerPlugin.java#L40

It would be great to be able to scan them all in on shot instead of running CLI multiple times.

**Comment by JensNercheKE** [comment]
Fixed in v1.8.1 which should be visible soon.
